name: NameColors
main: me.maximus1027.NameColors.Main
api-version: 1.18
version: 1.0

commands:
  namecoloradmin:
    aliases: [ncadmin]
    description: NameColors admin commands
    permission: namecolors.admin
    permission-message: Insufficient permission
  namecolor:
    description: NameColors player commands
    aliases: [namecolors, name]